name: Generate Cypress report

on: [push]

jobs:
  cypress-test:
    name: Run on Chrome 83
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.13.0-chrome95-ff94
    steps:
      - uses: actions/checkout@v2

      - name: Install cypresss and verify
        run: |
          npm ci
          $(npm bin)/cypress verify

      - name: Run Cypress test
        run: npm run test:chrome
#         continue-on-error: false

